---
secret_path_v2: "{{vault.path(/kv2_secret)}}"
secret_key_v2: "{{vault.key(/kv2_secret/key)}}"
sops_secret: "{{ sops.secret_file(/home/user/secrets/secret_file.yaml).secret_key(['s3']['access_key']) }}"
